### ISSUE TITLE
while using 3.16.0 with their new logger warns `Reading from `value` during component render.`

### ISSUE THREAD

**Issue by efstathiosntonas** [alantoa/react-native-awesome-slider#82]
Hey @alantoa,

after upgrading to reanimated@3.16.0 the console gives this warning: 

```
[Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.

If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
```

**Comment by alantoa** [comment]
thanks for the report, I'll try to update to the latest version.

**Comment by alantoa** [comment]
just fixed in the latest version.

**Comment by efstathiosntonas** [comment]
@alantoa according to the docs the logger config is for app devs only, not for modules since the app’s logger configuration will override the module’s config:

https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration#remarks

The logger does not help at all to spot where a value is used while rendering and it’s hard to track down what needs to be changed 😤

**Comment by alantoa** [comment]
good to know, that's sucks. I don't know where the warning is displayed. I'll take a look later when I have time.

**Comment by mbpictures** [comment]
Still have this issue in the current version, fixed it with this patch:
[react-native-awesome-slider+2.5.5.patch](https://github.com/user-attachments/files/17535065/react-native-awesome-slider%2B2.5.5.patch)

**Comment by alantoa** [comment]
I just released a new version of it, thanks guys!
https://www.npmjs.com/package/react-native-awesome-slider/v/2.5.6

**Comment by Noitham** [comment]
The warning is still visible with 2.5.6 on my end @alantoa

**Comment by alecgorge** [comment]
I am also seeing this in 2.9.0 after upgrading reanimated and expo as part of a move to expo 52. I'm having trouble debugging. All `.value` calls seem to be within `useCallback`, `useDerivedValue`, `useAnimatedStyle`, etc
